
import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    AlertTriangle, FileText, Activity, Layers, Calendar,
    Users, DollarSign, ArrowLeft, Download, Share2,
    MessageSquare, CheckCircle, Search, ChevronRight, Send
} from 'lucide-react';
import './Dashboard.css';

const Dashboard = ({ file, analysisData, onBack }) => {
    const {
        originalText, simplifiedText, riskScore, riskLevel,
        summary, entities, sections, fileSize, pageCount, uploadDate
    } = analysisData;

    const [activeTab, setActiveTab] = useState('original'); // original, simplified
    const [rightPanelTab, setRightPanelTab] = useState('risks'); // risks, summary, chat

    // Chat State
    const [chatInput, setChatInput] = useState('');
    const [chatHistory, setChatHistory] = useState([]);
    const [isTyping, setIsTyping] = useState(false);
    const chatEndRef = useRef(null);

    // Scroll to bottom of chat
    useEffect(() => {
        chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [chatHistory, isTyping]);

    const getRiskColor = (score) => {
        if (score < 30) return '#10b981'; // Green
        if (score < 70) return '#f59e0b'; // Yellow
        return '#ef4444'; // Red
    };

    const riskColor = getRiskColor(riskScore);

    // Handlers
    const handleShare = () => {
        navigator.clipboard.writeText(window.location.href);
        // In a real app, use a toast notification
        alert("Link copied to clipboard!");
    };

    const handleExport = () => {
        const content = `
ANALYSIS REPORT
File: ${file?.name || analysisData.fileName}
Date: ${new Date().toLocaleDateString()}
----------------------------------------
RISK ASSESSMENT
Score: ${riskScore}/100 (${riskLevel})
Issues Found: ${analysisData.riskFactors}

KEY TAKEAWAYS
${summary.map(s => `- ${s}`).join('\n')}

EXTRACTED ENTITIES
Dates: ${entities.dates.join(', ')}
Parties: ${entities.orgs.join(', ')}
Money: ${entities.money.join(', ')}

----------------------------------------
Generated by AI Legal Simplifier
        `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Report-${file?.name || 'Document'}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleSendMessage = (text) => {
        const message = text || chatInput;
        if (!message.trim()) return;

        // Add user message
        const newHistory = [...chatHistory, { type: 'user', text: message }];
        setChatHistory(newHistory);
        setChatInput('');
        setIsTyping(true);

        // Simulate AI response
        setTimeout(() => {
            let response = "I've analyzed the document. ";
            if (message.toLowerCase().includes('termination')) {
                response += "The termination clause allows either party to terminate with 30 days notice. There is no early termination fee specified.";
            } else if (message.toLowerCase().includes('fee') || message.toLowerCase().includes('cost')) {
                response += "I found references to a monthly service fee of $5,000, payable on the 1st of each month. Late fees are calculated at 1.5% per month.";
            } else if (message.toLowerCase().includes('liability')) {
                response += "Liability is capped at the total amount paid in the previous 12 months, except in cases of gross negligence or willful misconduct.";
            } else {
                response += "I can help clarify specific clauses or summarize sections. Could you be more specific regarding which part of the document you're interested in?";
            }

            setChatHistory(prev => [...prev, { type: 'ai', text: response }]);
            setIsTyping(false);
        }, 1500);
    };

    return (
        <div className="dashboard-container">
            {/* Header */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="dashboard-header"
            >
                <div className="header-left">
                    <button onClick={onBack} className="back-btn">
                        <ArrowLeft size={20} />
                        Back
                    </button>
                    <div className="file-info">
                        <h2 className="file-name">{file?.name || analysisData.fileName}</h2>
                        <div className="file-meta-row">
                            <span className="meta-tag">{fileSize}</span>
                            <span className="meta-tag">{pageCount} Pages</span>
                            <span className="meta-tag">Uploaded {new Date(uploadDate).toLocaleDateString()}</span>
                        </div>
                    </div>
                </div>
                <div className="header-actions">
                    <button className="action-btn" onClick={handleShare}>
                        <Share2 size={18} />
                        Share
                    </button>
                    <button className="action-btn primary" onClick={handleExport}>
                        <Download size={18} />
                        Export Report
                    </button>
                </div>
            </motion.div>

            <div className="dashboard-grid">
                {/* Left Panel: Document Viewer */}
                <div className="start-panel glass-card">
                    <div className="panel-tabs">
                        <button
                            className={`tab-btn ${activeTab === 'original' ? 'active' : ''}`}
                            onClick={() => setActiveTab('original')}
                        >
                            <FileText size={16} /> Original
                        </button>
                        <button
                            className={`tab-btn ${activeTab === 'simplified' ? 'active' : ''}`}
                            onClick={() => setActiveTab('simplified')}
                        >
                            <Activity size={16} /> Simplified
                        </button>
                    </div>

                    <div className="document-content-area custom-scrollbar">
                        <AnimatePresence mode="wait">
                            {activeTab === 'original' ? (
                                <motion.div
                                    key="original"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="doc-text original"
                                    dangerouslySetInnerHTML={{ __html: originalText }}
                                />
                            ) : (
                                <motion.div
                                    key="simplified"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="doc-text simplified"
                                >
                                    <div className="ai-badge">
                                        <CheckCircle size={14} /> AI Simplified
                                    </div>
                                    <div className="markdown-body">
                                        {simplifiedText}
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </div>

                {/* Right Panel: Intelligence Hub */}
                <div className="end-panel glass-card">
                    <div className="panel-tabs secondary">
                        <button
                            className={`tab-link ${rightPanelTab === 'risks' ? 'active' : ''}`}
                            onClick={() => setRightPanelTab('risks')}
                        >
                            Risks
                        </button>
                        <button
                            className={`tab-link ${rightPanelTab === 'summary' ? 'active' : ''}`}
                            onClick={() => setRightPanelTab('summary')}
                        >
                            Summary
                        </button>
                        <button
                            className={`tab-link ${rightPanelTab === 'chat' ? 'active' : ''}`}
                            onClick={() => setRightPanelTab('chat')}
                        >
                            Q&A
                        </button>
                    </div>

                    <div className="panel-content custom-scrollbar">
                        {rightPanelTab === 'risks' && (
                            <div className="risks-view">
                                {/* Overall Score */}
                                <div className="score-card">
                                    <div className="circular-chart-container">
                                        <svg viewBox="0 0 36 36" className="circular-chart sm">
                                            <path className="circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                            <path className="circle" strokeDasharray={`${riskScore}, 100`} stroke={riskColor} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                            <text x="18" y="20.35" className="percentage">{riskScore}</text>
                                        </svg>
                                    </div>
                                    <div className="score-details">
                                        <h4>{riskLevel} Risk Level</h4>
                                        <p>{analysisData.riskFactors} issues found</p>
                                    </div>
                                </div>

                                {/* Clause List */}
                                <div className="clauses-list">
                                    {sections.map((section, idx) => (
                                        <div key={idx} className="clause-card" style={{ borderLeft: `3px solid ${section.risk === 'High' ? '#ef4444' : section.risk === 'Medium' ? '#f59e0b' : '#10b981'}` }}>
                                            <div className="clause-header">
                                                <h5>{section.title}</h5>
                                                <span className={`risk-badge ${section.risk.toLowerCase()}`}>{section.risk}</span>
                                            </div>
                                            <p className="clause-snippet">{section.content.substring(0, 60)}...</p>
                                            {section.recommendation && (
                                                <div className="recommendation-box">
                                                    <strong>AI Suggestion:</strong> {section.recommendation}
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {rightPanelTab === 'summary' && (
                            <div className="summary-view">
                                <div className="summary-section">
                                    <h3>Key Takeaways</h3>
                                    <ul className="modern-list">
                                        {summary.map((point, i) => (
                                            <li key={i}>
                                                <ChevronRight size={16} className="bullet-icon" />
                                                {point}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                                <div className="summary-section">
                                    <h3>Extracted Entities</h3>
                                    <div className="entities-grid">
                                        <div className="entity-box">
                                            <span className="entity-label"><Calendar size={12} /> Dates</span>
                                            <div className="tags">{entities.dates.map((d, i) => <span key={i}>{d}</span>)}</div>
                                        </div>
                                        <div className="entity-box">
                                            <span className="entity-label"><DollarSign size={12} /> Money</span>
                                            <div className="tags">{entities.money.map((d, i) => <span key={i}>{d}</span>)}</div>
                                        </div>
                                        <div className="entity-box">
                                            <span className="entity-label"><Users size={12} /> Parties</span>
                                            <div className="tags">{entities.orgs.map((d, i) => <span key={i}>{d}</span>)}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}

                        {rightPanelTab === 'chat' && (
                            <div className="chat-view">
                                {chatHistory.length === 0 ? (
                                    <div className="chat-placeholder">
                                        <MessageSquare size={40} opacity={0.5} />
                                        <p>Ask questions about your document</p>
                                        <div className="suggested-questions">
                                            <button onClick={() => handleSendMessage("Explain the termination clause")}>"Explain the termination clause"</button>
                                            <button onClick={() => handleSendMessage("Are there any hidden fees?")}>"Are there any hidden fees?"</button>
                                            <button onClick={() => handleSendMessage("Summarize liability limits")}>"Summarize liability limits"</button>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="chat-history">
                                        {chatHistory.map((msg, i) => (
                                            <div key={i} className={`chat-message ${msg.type}`}>
                                                <div className="message-bubble">
                                                    {msg.text}
                                                </div>
                                            </div>
                                        ))}
                                        {isTyping && (
                                            <div className="chat-message ai">
                                                <div className="message-bubble typing">
                                                    <span>.</span><span>.</span><span>.</span>
                                                </div>
                                            </div>
                                        )}
                                        <div ref={chatEndRef} />
                                    </div>
                                )}
                                <div className="chat-input-area">
                                    <input
                                        type="text"
                                        placeholder="Type a question..."
                                        value={chatInput}
                                        onChange={(e) => setChatInput(e.target.value)}
                                        onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                                    />
                                    <button className="send-btn" onClick={() => handleSendMessage()}>
                                        <ArrowLeft size={16} style={{ transform: 'rotate(135deg)' }} />
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Dashboard;
